#!/usr/bin/env perl

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

no lib '.';  # CVE-2016-1238

use strict;
use warnings;
use English qw(-no_match_vars);

use Email::Address::XS ();

my $rc = 0;
for (@ARGV) {
    my $a = Email::Address::XS->parse_bare_address($_);
    if (not $a->is_valid) {
        print STDERR "bad addr-spec: $_\n";
        $rc = 1;
    } elsif ($a->format() ne $_) {
        print STDERR "non-canonical addr-spec: $_\n";
    } elsif ($a =~ /[\x80-\xFF]/) {
        print STDERR "non-ASCII chars in addr-spec: $_\n";
    } elsif ($a =~ /[\x00-\x1F\x7F]/) {
        print STDERR "control chars in addr-spec: $_\n";
    }
}
exit $rc;

# vim:ts=4 sts=4 sw=4 et
